interval: 5m
console: true
device: default

ruuvitags:
  "CC:CA:7E:52:CC:34": Backyard
  "FB:E1:B7:04:95:EE": Upstairs
  "E8:E0:C6:0B:B8:C5": Downstairs

influxdb:
  enabled: true
  addr: http://localhost:8086
  database: ruuvitag
  measurement: ruuvitag
  token: abc123

gcp:
  credentials: /home/pi/credentials.json
  project: ruuvitag
  pubsub:
    enabled: true
    topic: ruuvitag-measurements
